package com.cybersource.schemas.transaction_data.transactionprocessor;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-10T10:45:22.017+07:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "urn:schemas-cybersource-com:transaction-data:TransactionProcessor", name = "ITransactionProcessor")
@XmlSeeAlso({com.cybersource.schemas.transaction_data_1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ITransactionProcessor {

    @WebMethod(operationName = "runTransaction")
    public Response<com.cybersource.schemas.transaction_data_1.ReplyMessage> runTransactionAsync(

        @WebParam(partName = "input", name = "requestMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.141")
        com.cybersource.schemas.transaction_data_1.RequestMessage input
    );

    @WebMethod(operationName = "runTransaction")
    public Future<?> runTransactionAsync(

        @WebParam(partName = "input", name = "requestMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.141")
        com.cybersource.schemas.transaction_data_1.RequestMessage input,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.cybersource.schemas.transaction_data_1.ReplyMessage> asyncHandler
    );

    @WebMethod(action = "runTransaction")
    @WebResult(name = "replyMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.141", partName = "result")
    public com.cybersource.schemas.transaction_data_1.ReplyMessage runTransaction(

        @WebParam(partName = "input", name = "requestMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.141")
        com.cybersource.schemas.transaction_data_1.RequestMessage input
    );
}
